# Generated by Django 5.1.7 on 2025-03-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AgriExpert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Farmer', 'Magsasaka'), ('Expert', 'Eksperto')], default='Farmer', max_length=10)),
                ('proof_of_expertise', models.URLField(blank=True, null=True)),
                ('license_number', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Farmer', 'Magsasaka'), ('Expert', 'Eksperto')], default='Farmer', max_length=10)),
                ('farm_size', models.DecimalField(decimal_places=2, help_text='Lawak ng Sakahan (Hectares)', max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
