# Generated by Django 5.1.7 on 2025-03-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='expert',
            name='role',
            field=models.CharField(choices=[('Magsasaka', 'Magsasaka'), ('Eksperto', 'Eksperto')], default='Magsasaka', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='role',
            field=models.CharField(choices=[('Magsasaka', 'Magsasaka'), ('Eksperto', 'Eksperto')], default='Magsasaka', max_length=10),
        ),
    ]
