# Generated by Django 5.1.7 on 2025-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0003_admin_alter_expert_role_alter_farmer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterModelTable(
            name='expert',
            table='AgriExpert_expert',
        ),
        migrations.AlterModelTable(
            name='farmer',
            table='AgriExpert_farmer',
        ),
    ]
