# Generated by Django 5.1.7 on 2025-03-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0004_expert_position_expert_status_alter_expert_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/predictions/')),
                ('predicted_class', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgriExpert.farmer')),
            ],
            options={
                'db_table': 'AgriExpert_prediction_history',
            },
        ),
    ]
