# Generated by Django 5.1.7 on 2025-03-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0007_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
