# Generated by Django 5.1.7 on 2025-03-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0008_message_is_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='solution_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
