# Generated by Django 5.1.7 on 2025-03-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0009_message_solution_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='classification',
            field=models.CharField(blank=True, choices=[('Sakit', 'Sakit (Disease)'), ('Peste', 'Peste (Pest)')], max_length=10, null=True),
        ),
    ]
