# Generated by Django 5.1.7 on 2025-04-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0011_expertpost_comment_expertpostimage_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paksa', models.TextField()),
                ('deskripsyon', models.TextField()),
                ('ano_ang_nagagawa_nito', models.TextField()),
                ('bakit_at_saan_ito_nangyayari', models.TextField()),
                ('paano_ito_matutukoy', models.TextField()),
                ('bakit_ito_mahalaga', models.TextField()),
                ('paano_ito_pangangasiwaan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
