# Generated by Django 5.1.7 on 2025-04-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0012_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='image',
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
