# Generated by Django 5.1.7 on 2025-05-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0013_remove_predictionhistory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgriExpert.library'),
        ),
    ]
