# Generated by Django 5.1.7 on 2025-05-01 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0014_predictionhistory_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgriExpert.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AgriExpert.farmerpost')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_solution', models.BooleanField(default=False)),
                ('solution_highlighted', models.BooleanField(default=False)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AgriExpert.expert')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AgriExpert.farmer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgriExpert.farmerpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('expert__isnull', True), ('farmer__isnull', False)), models.Q(('expert__isnull', False), ('farmer__isnull', True)), _connector='OR'), name='farmer_or_expert_comment')],
            },
        ),
        migrations.CreateModel(
            name='FarmerUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AgriExpert.expert')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AgriExpert.farmer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgriExpert.farmerpost')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('expert__isnull', True), ('farmer__isnull', False)), models.Q(('expert__isnull', False), ('farmer__isnull', True)), _connector='OR'), name='farmer_or_expert_upvote'), models.UniqueConstraint(condition=models.Q(('farmer__isnull', False)), fields=('post', 'farmer'), name='unique_farmer_upvote'), models.UniqueConstraint(condition=models.Q(('expert__isnull', False)), fields=('post', 'expert'), name='unique_expert_upvote')],
            },
        ),
    ]
