# Generated by Django 5.1.7 on 2025-11-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0015_farmerpost_farmerpostimage_farmerpostcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
