# Generated by Django 5.1.7 on 2025-11-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriExpert', '0017_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('expert', 'Expert'), ('farmer', 'Farmer')], max_length=20)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_tracking', to='AgriExpert.announcement')),
            ],
            options={
                'db_table': 'AgriExpert_announcement_views',
                'unique_together': {('announcement', 'user_id', 'user_type')},
            },
        ),
    ]
